config/routes.rb
Rails.application.routes.draw do
  root 'mixtapes#index'
  get 'mixtapes/alphabetize', to: 'mixtapes#alphabetize'
  get 'mixtapes/year_sort', to: 'mixtapes#year_sort'
  get 'mixtapes/subgenres', to: 'mixtapes#subgenres'
  get 'mixtapes/search', to: 'mixtapes#search'

  resources :mixtapes, :only => [:index, :show] do
    patch '/rate', to: 'mixtapes#rate'
    resources :reviews, :except => [:index]
  end

  resources :users do
    resources :mixtapes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
  validates :title, :image, :subgenre, :year, :presence => true
  belongs_to :user
  has_many :reviews
  # has_many :users, through: :reviews
  # after_initialize :set_defaults, unless: :persisted?
  #
  # def set_defaults
  #   self.rating_sum = 0 if self.new_record?
  #   self.rating_count = 0 if self.new_record?
  # end

  def rating
    if self.rating_sum > 0 && self.rating_count > 0
      (self.rating_sum / self.rating_count).round(2)
    end
  end

  def new_rating(rating_add)
    self.rating_sum += rating_add.to_i
    self.rating_count += 1
  end

  def self.alphabetize
    self.order("lower(title)")
  end

  def self.year_sort
    self.order(year: :desc)
  end

  def self.unique_subgenres
    self.all.map(&:subgenre).uniq
  end

  def self.find_by_subgenre(genre)
     self.where(:subgenre => genre)
  end

  def self.search_query(search_input)
    self.basic_search(search_input)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :content, :presence => true
  belongs_to :mixtape
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  has_many :mixtapes
  # has_many :reviews
  # has_many :mixtapes, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
  def index
    if Mixtape.all.length > 0
      @featured = Mixtape.order('RANDOM()').first
      allMixtapes = []
      Mixtape.all.each do |mixtape|
        allMixtapes.push(mixtape)
      end
      allMixtapes.delete_at(allMixtapes.index(@featured))
      @mixtapes = allMixtapes
    else
      @mixtapes = Mixtape.all
    end

    @mixtapes = Mixtape.order(params[:alphabetize])
  end

  def show
    @mixtape = Mixtape.find(params[:id])
    @rating = @mixtape.rating
    @review = @mixtape.reviews.new
  end

  def new
    @user = User.find(params[:user_id])
    @mixtape = @user.mixtapes.new
  end

  def create
    @user = User.find(params[:user_id])
    @mixtape = @user.mixtapes.new(mixtape_params)
    if @mixtape.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @mixtape = Mixtape.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @mixtape = Mixtape.find(params[:id])
    if @mixtape.update (mixtape_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @mixtape = Mixtape.find(params[:id])
    @mixtape.destroy
    redirect_to user_path(@user)
  end

  def rate
    @mixtape = Mixtape.find(params[:mixtape_id])
    @mixtape.new_rating(rate_params[:rating])
    @mixtape.save

    redirect_to mixtape_path(@mixtape)
  end

  def alphabetize
    @mixtapes = Mixtape.alphabetize
    render :index
  end

  def year_sort
    @mixtapes = Mixtape.year_sort
    render :index
  end

  def subgenres
    @mixtapes = Mixtape.find_by_subgenre(subgenre_params[:subgenre])
    render :index
  end

  def search
    @mixtapes = Mixtape.search_query(search_params[:search_input])
    render :index
  end

private
  def mixtape_params
    params.require(:mixtape).permit(:title, :image, :subgenre, :year)
  end

  def rate_params
    params.permit(:rating)
  end

  def subgenre_params
    params.permit(:subgenre)
  end

  def search_params
    params.permit(:search_input)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @mixtape = Mixtape.find(params[:mixtape_id])
    @review = @mixtape.reviews.new(review_params)
    if @review.save
      redirect_to mixtape_path(@mixtape)
    else
      flash[:notice] = "Please fill in your review"
      redirect_to mixtape_path(@mixtape)
    end
  end

private
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.mixtapes.each do |mixtape|
      mixtape.destroy
    end
    @user.destroy
    redirect_to users_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Fiyah Mixtapes Inc.', mixtapes_path, :class => 'navbar-brand'%>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "All Users", users_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/mixtapes/_form.html.erb
<%= render 'layouts/errors', :object => @mixtape %>

<%= form_for [@user, @mixtape] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.label :subgenre %>
  <%= f.text_field :subgenre %>
  <%= f.label :year %>
  <%= f.number_field :year %>
  <%= f.submit %>
<% end %>

app/views/mixtapes/edit.html.erb
<h1>Edit Mixtape</h1>

<%= render 'form' %>

app/views/mixtapes/index.html.erb
<h1>Mixtapes</h1>

<%= link_to 'Remove Filtering and Sorting', mixtapes_path %>
<%= form_tag(mixtapes_search_path, method: 'get') do %>
  <%= label_tag 'Search Input' %>
  <%= text_field_tag :search_input %>
  <%= submit_tag 'Search' %>
<% end %>
<!-- <%= button_to 'Alphabetize', mixtapes_alphabetize_path, method: 'get' %> -->
<%= link_to 'Alphabetize', :alphabetize => 'title' %>
<%= button_to 'Sort By Year', mixtapes_year_sort_path, method: 'get' %>

<div>
  <%= form_tag(mixtapes_subgenres_path, method: 'get') do %>
    <%= label_tag 'Select Subgenre' %><br>
    <%= select_tag :subgenre, options_for_select(Mixtape.unique_subgenres) %>
    <%= submit_tag 'Filter' %>
  <% end %>
</div>

<% if @featured %>
  <div class="featured">
    <h2>Featured</h2>
    <h3><%= link_to @featured.title, mixtape_path(@featured) %></h3>
    <%= image_tag @featured.image %>
  </div>
<% end %>
<ul>
<% @mixtapes.each do |mixtape| %>
  <li><%= link_to mixtape.title, mixtape_path(mixtape) %> | <%= mixtape.year %></li>
  <hr>
<% end %>
</ul>

app/views/mixtapes/new.html.erb
<h1>Add New Mixtape</h1>

<%= render 'form' %>

app/views/mixtapes/show.html.erb
<h1><%= @mixtape.title %></h1>

<%= image_tag @mixtape.image %>

<p><%= @mixtape.year %></p>
<p><%= @mixtape.subgenre %></p>

<p>Rating: <%= @rating %></p>

<h5>Rate This Mixtape</h5>

<%= form_tag(mixtape_rate_path(@mixtape), method: 'patch') do %>
  <%= radio_button_tag :rating, 1 %>
  <%= label_tag :rating, '1', :value => 1 %><br>
  <%= radio_button_tag :rating, 2 %>
  <%= label_tag :rating, '2', :value => 2 %><br>
  <%= radio_button_tag :rating, 3 %>
  <%= label_tag :rating, '3', :value => 3 %><br>
  <%= radio_button_tag :rating, 4 %>
  <%= label_tag :rating, '4', :value => 4 %><br>
  <%= radio_button_tag :rating, 5 %>
  <%= label_tag :rating, '5', :value => 5 %><br>
  <%= submit_tag("Rate") %>
<% end %>
<hr>

<h3>Reviews</h3>
<% @mixtape.reviews.each do |review| %>
  <p><%= review.content %></p>
  <hr>
<% end %>

<%= content_tag(:div, notice, class: 'notice') if notice %>

<%= render 'reviews/form' , :object => @review%>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :object => @review %>

<%= form_for [@mixtape, @review] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

<%= link_to "Create a User", new_user_path %>

app/views/users/new.html.erb
<h1>Create a User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<ul>
  <% @user.mixtapes.each do |mixtape| %>
    <li><%=  mixtape.title %> |  <%= link_to 'Edit', edit_user_mixtape_path(@user, mixtape) %> | <%= link_to "Delete", user_mixtape_path(@user, mixtape),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %> </li>
  <% end %>
</ul>

<p><%= link_to "Add Mixtape", new_user_mixtape_path(@user) %> </p>
<p><%= link_to "Edit User", edit_user_path(@user) %></p>
<p><%= link_to "Delete User", user_path(@user),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>